# Generated by Django 2.0 on 2019-03-19 16:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='company',
            table=None,
        ),
    ]
