# Generated by Django 2.0 on 2019-03-19 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0003_auto_20190319_2113'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('CompanyName', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('CompanyTitle', models.CharField(max_length=50)),
            ],
        ),
        migrations.DeleteModel(
            name='Article',
        ),
    ]
