# Generated by Django 2.0 on 2019-03-19 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0004_auto_20190319_2116'),
    ]

    operations = [
        migrations.CreateModel(
            name='public',
            fields=[
                ('publicName', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('publicTitle', models.CharField(max_length=50)),
            ],
        ),
    ]
