# Generated by Django 2.0 on 2019-03-19 16:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0005_public'),
    ]

    operations = [
        migrations.DeleteModel(
            name='public',
        ),
    ]
