# Generated by Django 2.0 on 2019-03-19 18:16

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('login', '0006_delete_public'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='user_companies',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
