# Generated by Django 2.0 on 2019-03-19 18:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0008_auto_20190319_2326'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comapnies_registered',
            old_name='user_companies',
            new_name='user',
        ),
    ]
