# Generated by Django 2.0 on 2019-03-19 18:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0009_auto_20190319_2329'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comapnies_registered',
            name='companies',
        ),
        migrations.RemoveField(
            model_name='comapnies_registered',
            name='user',
        ),
        migrations.DeleteModel(
            name='comapnies_registered',
        ),
    ]
