# Generated by Django 2.0 on 2019-03-19 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0014_auto_20190320_0017'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='user',
        ),
        migrations.AddField(
            model_name='registration',
            name='user',
            field=models.CharField(max_length=50, null=True, verbose_name='auth.User'),
        ),
    ]
