# Generated by Django 2.0 on 2019-03-19 19:35

import django.contrib.auth.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0015_auto_20190320_0034'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registration',
            name='user',
            field=models.CharField(max_length=50, null=True, verbose_name=django.contrib.auth.models.User),
        ),
    ]
