# Generated by Django 2.0 on 2019-03-19 19:59

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('login', '0019_registration_company'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='registration',
            unique_together={('users', 'company')},
        ),
    ]
